project:
  type: website

website:
  title: "Student-GPA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - model.qmd
      - Sources.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



